# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](https://github.com/cheauyuin/6m-data-1.6-intro-numpy/blob/main/assets/numpy_vs_python_list.png?raw=1)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [1]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

NumPy Vectorized Multiplication (my_arr * 2):
1.42 ms ± 86.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
61.5 ms ± 3.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](https://github.com/cheauyuin/6m-data-1.6-intro-numpy/blob/main/assets/numpy_ndarray.png?raw=1)

In [3]:
# [DEMO] Creating arrays from sequences
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)


print(f"Array 1:\n{arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}, Dimensions: {arr1.ndim}")

print(f"\n\nArray 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

Array 1:
[6.  7.5 8.  0.  1. ]
Shape: (5,), Dtype: float64, Dimensions: 1


Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [5]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [7]:
# Your code here
arr1 = np.ones((3, 4))
print("Original arr1:\n", arr1)
print("Casted to float32:\n", arr1.astype(np.float32))

arr2 = np.array(['1.25', '-9.6', '42'])
print("Original arr2:\n", arr2)
print("Casted to float32:\n", arr2.astype(np.float32))


Original arr1:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Casted to float32:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Original arr2:
 ['1.25' '-9.6' '42']
Casted to float32:
 [ 1.25 -9.6  42.  ]


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](https://github.com/cheauyuin/6m-data-1.6-intro-numpy/blob/main/assets/vectorization.png?raw=1)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [11]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax.

### 2D Array Indexing Syntax
![2d_array_indexing](https://github.com/cheauyuin/6m-data-1.6-intro-numpy/blob/main/assets/ndarray_axis_index.png?raw=1)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [12]:
# [DEMO] Slicing views
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]

First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [ ]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [13]:
# Your code here
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

not_bob_mask = (names != 'Bob')
print("Mask (not Bob):", not_bob_mask)
bob_or_will = (names == 'Bob') | (names == 'Will')
print("Bob or Will's scores:\n", scores[bob_or_will])
scores[scores < 80] = 0
print("Scores less than 80 set to 0:\n", scores)



Mask (not Bob): [False  True  True False  True  True  True]
Bob or Will's scores:
 [[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]
Scores less than 80 set to 0:
 [[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


In [14]:
# 1. Select all scores where name is NOT 'Bob'
print("Scores where name is NOT Bob:")
print(scores[names != 'Bob'])

# Select scores for 'Bob' or 'Will' using the | operator.
print("\nScores for Bob or Will:")
print(scores[(names == 'Bob') | (names == 'Will')])

# 3. Set all scores less than 80 to 0
scores[scores < 80] = 0
print("\nScores after replacing values less than 80 with 0:")
print(scores)


Scores where name is NOT Bob:
[[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [  0  80]]

Scores for Bob or Will:
[[  0  80]
 [ 95 100]
 [100   0]
 [ 85  92]]

Scores after replacing values less than 80 with 0:
[[  0  80]
 [ 85  90]
 [ 95 100]
 [100   0]
 [ 85  92]
 [ 95  80]
 [  0  80]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays.

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [15]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [[ 0.16541819  0.11528239  0.82272985  0.58563664]
 [ 1.4934923   1.01631329 -0.45741044  0.92642899]
 [ 0.74532943  0.55730153  0.06747023  2.50655007]]

Mean down rows (axis=0): [0.80141331 0.56296574 0.14426321 1.33953857]
Sum across columns (axis=1): [1.68906708 2.97882414 3.87665126]


## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](https://github.com/cheauyuin/6m-data-1.6-intro-numpy/blob/main/assets/matrix_multiplication.png?raw=1)

In [16]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [24]:
# Your code here
arr1 = np.arange(15).reshape((3, 5))
print("arr1:\n", arr1)

row_averages = arr1.mean(axis=1)
print("\nRow averages:", row_averages)

distinct_elements_arr = np.unique(arr1)
print("\nDistinct elements in arr1:", distinct_elements_arr)

arr_transposed = arr1.T
print("\nTransposed arr1 (New shape will be (5, 3)):\n", arr_transposed)

print("\nShape of transposed array", arr_transposed.shape)


arr1:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Row averages: [ 2.  7. 12.]

Distinct elements in arr1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Transposed arr1 (New shape will be (5, 3)):
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

Shape of transposed array (5, 3)


### 🛠️ Exercise 5: Array Creation and Inspection

In [4]:
import numpy as np
# A 2D array of shape (4, 3) filled with 1.5
arr_2d_float = np.full((4, 3), 1.5)
print("\n2D Array (4, 3) filled with 1.5:")
print(arr_2d_float)
print(f"Shape: {arr_2d_float.shape}, Dtype: {arr_2d_float.dtype}, Dimensions: {arr_2d_float.ndim}")

# Convert the (4, 3) float array to integers
arr_2d_int = arr_2d_float.astype(int)
print("\nConverted 2D Array to int:")
print(arr_2d_int)
print(f"Shape: {arr_2d_int.shape}, Dtype: {arr_2d_int.dtype}, Dimensions: {arr_2d_int.ndim}")


2D Array (4, 3) filled with 1.5:
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Shape: (4, 3), Dtype: float64, Dimensions: 2

Converted 2D Array to int:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (4, 3), Dtype: int64, Dimensions: 2


In [1]:
import numpy as np
# A 3D array of zeros with shape (2, 2, 3)
arr_3d_zeros = np.zeros((2, 2, 3))
print("\n3D Array of zeros with shape (2, 2, 3):")
print(arr_3d_zeros)
print(f"Shape: {arr_3d_zeros.shape}, Dtype: {arr_3d_zeros.dtype}, Dimensions: {arr_3d_zeros.ndim}")


3D Array of zeros with shape (2, 2, 3):
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
Shape: (2, 2, 3), Dtype: float64, Dimensions: 3


### When to prefer `float` vs `int` in real analyst work:

*   **Integers (`int`)** are best used for discrete quantities, counts, or identifiers that cannot have fractional parts. Examples include:
    *   Number of items sold (e.g., you can't sell half a product).
    *   Customer IDs, order numbers.
    *   Age (in whole years).
    *   Ranks or categories (if represented numerically).
    
*   **Floating-point numbers (`float`)** are used for continuous data where precision beyond whole numbers is required. Examples include:
    *   Prices or monetary values (e.g., $1.99, $100.50).
    *   Measurements (e.g., height, weight, temperature, time, scientific readings).
    *   Calculated ratios, percentages, or averages.
    *   Coordinates (latitude, longitude).

Choosing the correct data type is crucial for accuracy, memory efficiency, and preventing unexpected behavior in calculations.